---
name: ğŸ·ï¸ Github Release
on:
  workflow_dispatch:

env:
  CI: ${{ vars.CI }}
  HUSKY: ${{ vars.HUSKY }}

jobs:
  github-release:
    name: ğŸ·ï¸ Github Release
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”‘ Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: ğŸ”§ Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
          package_json_file: package.json
          run_install: false

      - name: ğŸŒ Setup Node.js
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          scope: "@maiar-ai"
          cache: pnpm

      - name: ğŸ“¦ Install Dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: ğŸ”– Github Release (Tag + Release)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm nx:release
